from returns.interfaces.unwrappable import Unwrappable as Unwrappable
from typing import Any

class UnwrapFailedError(Exception):
    halted_container: Any = ...
    def __init__(self, container: Unwrappable) -> None: ...

class ImmutableStateError(AttributeError): ...
