from typing import Awaitable, Generator

class ReAwaitable:
    def __init__(self, coro: Awaitable[_ValueType]) -> None: ...
    def __await__(self) -> Generator[None, None, _ValueType]: ...

def reawaitable(coro: _FunctionCoroType) -> _FunctionCoroType: ...
