from typing import Any, Dict, NoReturn

class Immutable:
    def __copy__(self) -> Immutable: ...
    def __deepcopy__(self, memo: Dict[Any, Any]) -> Immutable: ...
    def __setattr__(self, attr_name: str, attr_value: Any) -> NoReturn: ...
    def __delattr__(self, attr_name: str) -> NoReturn: ...
