from mypy.plugin import Plugin
from typing import Optional, Type

class _ReturnsPlugin(Plugin):
    def get_function_hook(self, fullname: str) -> Optional[_FunctionCallback]: ...
    def get_attribute_hook(self, fullname: str) -> Optional[_AttributeCallback]: ...
    def get_method_signature_hook(self, fullname: str) -> Optional[_MethodSigCallback]: ...
    def get_method_hook(self, fullname: str) -> Optional[_MethodCallback]: ...

def plugin(version: str) -> Type[Plugin]: ...
