from typing import Any, Iterator

class ReturnsAsserts:
    def assert_equal(self, first: Any, second: Any, *, deps: Any=..., backend: str=...) -> None: ...
    def is_error_handled(self, container: Any) -> bool: ...
    def assert_trace(self, trace_type: _ReturnsResultType, function_to_search: _FunctionType) -> Iterator[None]: ...

def returns(_patch_containers: Any) -> ReturnsAsserts: ...
def pytest_configure(config: Any) -> None: ...

class _PatchedContainer:
    @classmethod
    def containers_to_patch(cls: Any) -> tuple: ...
    @classmethod
    def error_handler(cls: Any, original: Any) -> Any: ...
    @classmethod
    def copy_handler(cls: Any, original: Any) -> Any: ...

class _DesiredFunctionFound(BaseException): ...
