from returns.primitives.laws import Lawful as Lawful
from typing import Any, Dict, Iterator, NamedTuple, Optional, Type

class _Settings(NamedTuple):
    settings_kwargs: Dict[str, Any]
    use_init: bool

def check_all_laws(container_type: Type[Lawful], *, settings_kwargs: Optional[Dict[str, Any]]=..., use_init: bool=...) -> None: ...
def container_strategies(container_type: Type[Lawful], settings: _Settings) -> Iterator[None]: ...
def maybe_register_container(container_type: Type[Lawful], use_init: bool) -> Iterator[None]: ...
def pure_functions() -> Iterator[None]: ...
def type_vars() -> Iterator[None]: ...
