from mypy.plugin import FunctionContext as FunctionContext, MethodContext as MethodContext, MethodSigContext as MethodSigContext
from mypy.types import CallableType as CallableType, Type as MypyType

def analyze(ctx: FunctionContext) -> MypyType: ...
def infer(ctx: MethodContext) -> MypyType: ...
def signature(ctx: MethodSigContext) -> CallableType: ...
