from typing import Any, Callable

def partial(func: Callable[..., _ReturnType], *args: Any, **kwargs: Any) -> Callable[..., _ReturnType]: ...
def curry(function: Callable[..., _ReturnType]) -> Callable[..., _ReturnType]: ...
